deploy-ecs:
  needs: ecr-push-lambda  # after image push
  runs-on: ubuntu-latest
  steps:
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: services/task-definition.json  # create this file
        service: ecr-ecs-demo-service
        cluster: ecr-ecs-demo
        wait-for-service-stability: true
